#!/bin/bash
set +e

mkdir -p /tmp/var/sessions/
cp -rf lumen/storage /tmp

export STORAGE_PATH=/tmp/storage

#/code/.fun/root/usr/bin/php8.0 -c /code /code/http.php
#/code/.fun/root/usr/bin/php7.4 /code/lumen/bin/laravels start

# /code/.fun/root/usr/bin/php7.4 -c /code -S 0.0.0.0:${FC_SERVER_PORT} -t /code

/code/.fun/root/usr/bin/php8.0 -S 0.0.0.0:9000 -t /code

#/code/.fun/root/usr/bin/php8.0 /code/mark-demo/serve.php start
#php /code/mark-demo/proxy.php start