ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  customruntime:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: helloworld
      Role: >-
        acs:ram::1928687499779704:role/aliyunfcgeneratedrole-cn-hongkong-customruntime
      VpcConfig:
        VpcId: vpc-j6ccne7rjafmtgh7zrk4o
        VSwitchIds:
          - vsw-j6conwtcfurx5uhogyb2j
        SecurityGroupId: sg-j6ci9xnerwj6bvj0e4ej
      NasConfig:
        UserId: 10002
        GroupId: 10002
        MountPoints:
          - ServerAddr: '1213e74b022-hag27.cn-hongkong.nas.aliyuncs.com:/php-swoole'
            MountDir: /mnt/nas
      InternetAccess: true
    php-swoole:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: custom
        Timeout: 1
        MemorySize: 128
        InstanceConcurrency: 1
        EnvironmentVariables:
          LD_LIBRARY_PATH: >-
            /mnt/nas/root/usr/lib:/mnt/nas/root/usr/lib/x86_64-linux-gnu:/mnt/nas/root/lib/x86_64-linux-gnu:/mnt/nas/root/usr/lib64:/code/.fun/root/usr/lib:/code/.fun/root/usr/lib/x86_64-linux-gnu:/code/.fun/root/lib/x86_64-linux-gnu:/code/.fun/root/usr/lib64:/code:/code/lib:/usr/local/lib
          NODE_PATH: >-
            /code/.fun/root/usr/local/bin:/code/.fun/root/usr/local/sbin:/code/.fun/root/usr/bin:/code/.fun/root/usr/sbin:/code/.fun/root/sbin:/code/.fun/root/bin:/code/.fun/python/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin:/mnt/nas/root/usr/local/bin:/mnt/nas/root/usr/local/sbin:/mnt/nas/root/usr/bin:/mnt/nas/root/usr/sbin:/mnt/nas/root/sbin:/mnt/nas/root/bin:/mnt/nas/node_modules/.bin:/mnt/nas/node_modules:/usr/local/lib/node_modules
          PATH: >-
            /code/.fun/root/usr/local/bin:/code/.fun/root/usr/local/sbin:/code/.fun/root/usr/bin:/code/.fun/root/usr/sbin:/code/.fun/root/sbin:/code/.fun/root/bin:/code/.fun/python/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin:/mnt/nas/root/usr/local/bin:/mnt/nas/root/usr/local/sbin:/mnt/nas/root/usr/bin:/mnt/nas/root/usr/sbin:/mnt/nas/root/sbin:/mnt/nas/root/bin:/mnt/nas/node_modules/.bin
          PYTHONPATH: >-
            /mnt/nas/python/lib/python2.7/site-packages:/mnt/nas/python/lib/python3.6/site-packages
          PYTHONUSERBASE: /code/.fun/python
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: anonymous
            Methods:
              - HEAD
              - POST
              - PUT
              - GET
              - DELETE
    phpinfo:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: php7.2
        Timeout: 1
        MemorySize: 128
        InstanceConcurrency: 1
        EnvironmentVariables: {}
      Events:
        http:
          Type: HTTP
          Properties:
            AuthType: anonymous
            Methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
