ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  customruntime:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: helloworld
      Role: >-
        acs:ram::1928687499779704:role/aliyunfcgeneratedrole-cn-hongkong-customruntime
      VpcConfig:
        VpcId: vpc-j6ccne7rjafmtgh7zrk4o
        VSwitchIds:
          - vsw-j6cv3y42xzcbt7izy6j81
        SecurityGroupId: sg-j6ci9xnerwj6bvj0e4ej
      NasConfig:
        UserId: 10002
        GroupId: 10002
        MountPoints:
          - ServerAddr: '12ff5b49627-xoj22.cn-hongkong.nas.aliyuncs.com:/'
            MountDir: /mnt/nas
      InternetAccess: true
    php-swoole:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: custom
        Timeout: 60
        MemorySize: 512
        EnvironmentVariables:
          LD_LIBRARY_PATH: >-
            /mnt/nas/root/usr/lib:/mnt/nas/root/usr/lib/x86_64-linux-gnu:/mnt/nas/root/lib/x86_64-linux-gnu:/mnt/nas/root/usr/lib64:/code/.fun/root/usr/lib:/code/.fun/root/usr/lib/x86_64-linux-gnu:/code/.fun/root/lib/x86_64-linux-gnu:/code/.fun/root/usr/lib64:/code:/code/lib:/usr/local/lib:/mnt/nas/usr/lib:/mnt/nas/usr/lib/x86_64-linux-gnu:/mnt/nas/lib/x86_64-linux-gnu:/mnt/nas/usr/lib64
          PATH: >-
            /code/.fun/root/usr/local/bin:/code/.fun/root/usr/local/sbin:/code/.fun/root/usr/bin:/code/.fun/root/usr/sbin:/code/.fun/root/sbin:/code/.fun/root/bin:/code/.fun/python/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin:/mnt/nas/usr/local/bin:/mnt/nas/usr/local/sbin:/mnt/nas/usr/bin:/mnt/nas/usr/sbin:/mnt/nas/sbin:/mnt/nas/bin
          PYTHONPATH: >-
            /mnt/nas/python/lib/python2.7/site-packages:/mnt/nas/python/lib/python3.6/site-packages
          PYTHONUSERBASE: /code/.fun/python
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: anonymous
            Methods:
              - HEAD
              - POST
              - PUT
              - GET
              - DELETE
